export const defaultNamespace = {};
export const PARENT = Symbol('Target Parents');
export const CHILDREN = Symbol('Target Children');
export const newListenerEvent = Symbol('New listener event id');
export const removeListenerEvent = Symbol('Remove listener event id');
export const addParentEvent = Symbol('Add parent event id');
export const removeParentEvent = Symbol('Remove parent listener event id');
export const addChildEvent = Symbol('Add child event id');
export const removeChildEvent = Symbol('Remove child event id');